[username]
disabled = false
show_always = true

[hostname]
ssh_only = false
trim_at = '.'

[kubernetes]
disabled = false

contexts = [
    { context_pattern = "rancher-desktop", style = "cyan", symbol = "ğŸ³ ", context_alias = "docker" },
    { context_pattern = "k3s-raspberry", style = "green", symbol = "ğŸ® " },
    { context_pattern = "k3s-proxmox", style = "green", symbol = "ğŸ® " },
]

[directory]
truncate_to_repo = false
truncation_length = 2
truncation_symbol = 'â€¦/'

[azure]
disabled = false
format = 'on [$symbol($subscription)]($style) '
symbol = 'ó° … '
style = 'blue bold'

[aws]
format = 'on [$symbol($profile )(\($region\) )]($style)'
style = 'bold yellow'
symbol = 'ïƒ¯  '
#symbol = 'ğŸ…° '
#symbol = 'ï‰° '

[git_branch]
symbol = 'ï˜ '

[golang]
symbol = 'î˜§ '
